GALLERYDIR=../../../../../../../..
PLATFORM=$(GALLERYDIR)/modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform
XSLFILE = $(PLATFORM)/postgres/PostgreSQL.xsl
include $(PLATFORM)/GNUmakefile.inc
