GALLERYDIR=../../../../../../../..
PLATFORM=$(GALLERYDIR)/modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform
XSLFILE = $(PLATFORM)/mysql/MySQL.xsl
include $(PLATFORM)/GNUmakefile.inc
