GALLERYDIR=../../../../../../../..
PLATFORM=$(GALLERYDIR)/modules/core/classes/GalleryStorage/DatabaseStorage/schema/platform
XSLFILE = $(PLATFORM)/oracle/Oracle.xsl
include $(PLATFORM)/GNUmakefile.inc
